spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/newsmanage?serverTimezone=GMT%2B8&useSSL=false
        username: admin
        password: 123456
    #reids
#     redis:
#         database: 0
#         host: 127.0.0.1
#         port: 6379
#         password: 
#         timeout: 0
# #    集群环境打开下面注释，单机不需要打开
# #    cluster:
# #      集群信息
# #      nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
# #      #默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
# #      maxRedirects: 3
#         jedis:
#             pool:
#                 max-active: 8
#                 min-idle: 0
#                 max-idle: 8
#                 max-wait: -1
# mybatis-plus配置
# mybatis-plus:
#   mapper-locations:
#   - classpath*:mapper/**/*.xml
#   type-aliases-package: com.news.web.module.entity
# mybatis配置
mybatis:
    #配置mapper xml文件所在的路径
    mapper-locations: classpath*:mapper/**/*.xml
    #配置映射类所在的包名
    type-aliases-package: com.news.web.module.entity

# tomcat启动端口
server:
  port: 8081